%% Graphical interface for signal visualization and interaction with ELEMYO sensors
% 2020-06-15 by ELEMYO (https://github.com/ELEMYO/Matlab_GUI)
% 
% Changelog:
%     2020-06-15 - initial release

%% Code is placed under t he MIT license
% Copyright (c) 2018 ELEMYO
% 
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
% 
% The above copyright notice and this permission notice shall be included in
% all copies or substantial portions of the Software.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
% THE SOFTWARE.
% ===============================================

%% Main graphics window
Fig = figure('units','normalized', ...
    'outerposition', [0.1 0.1 0.8 0.8], ...
    'MenuBar', 'none', ...
    'Name', 'EMG/ECG/EEG - Analyser | Elemyo', ...
    'NumberTitle', 'off');

hp = uipanel('Position',[.0 .0 1 1], ...
    'BorderType', 'none');     
hsp1 = uipanel('Parent',hp,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'Position',[.0 .5 1 .5], ...
    'BorderType', 'none');
hsp12 = uipanel('Parent',hp,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'Position',[.0 .14 0.5 .38], ...
    'BorderType', 'none');
hsp13 = uipanel('Parent',hp,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'Position',[.5 .14 1 .38], ...
    'BorderType', 'none');
hsp2 = uipanel('Parent',hp,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'Position',[0 0 1 .15], ...
    'BorderType', 'none');
hsp21 = uipanel('Parent',hsp2,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'Position',[0 0 .3 1], ...
    'BorderType', 'none');
hsp22 = uipanel('Parent',hsp2,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'Position',[.3 0 .7 1], ...
    'BorderType', 'none');

%% Logo
% ax = axes('Parent',hsp1,...
%     'Units','normalized', ...
%     'Position',[.03 .89 .11 .099], ...
%     'Box', 'off');
% imshow('logo.png');
% set(ax,'Visible', 'off');

%% Axes of plot output
axes('Parent',hsp1,...
    'Tag', 'main_axes', ...
    'Units', 'normalized', ...
    'Position',[.05 .16 .92 .75], ...
    'NextPlot','add',...
    'Xlim', [1 10], ...
    'Ylim', [0 5], ...
    'Color', [25/255 25/255 25/255], ...
    'Xcolor', [0.6 0.6 0.6], ...
    'YColor', [0.6 0.6 0.6], ...
    'Box', 'on',...
    'XGrid', 'on', ...
    'YGrid', 'on');

xlabel('Time (s)');
ylabel('Data');

%% Graph
SensorData = plot(0,0, 'Color', [0.4 1 1], 'LineWidth', 1);

%% Axes of plot output
axes('Parent',hsp12,...
    'Tag', 'main_axes2', ...
    'Units', 'normalized', ...
    'Position',[.1 .17 .85 .78], ...
    'NextPlot','add',...
    'Xlim', [0 120], ...
    'Ylim', [0 0.15], ...
    'Color', [25/255 25/255 25/255], ...
    'Xcolor', [0.6 0.6 0.6], ...
    'YColor', [0.6 0.6 0.6], ...
    'Box', 'on',...
    'XGrid', 'on', ...
    'YGrid', 'on');

xlabel('Time (s)');
ylabel('Data');

%% Graph
SensorData2 = plot(0,0, 'Color', [0.4 1 1], 'LineWidth', 1);

%% Axes of plot output
axes('Parent',hsp13,...
    'Tag', 'main_axes3', ...
    'Units', 'normalized', ...
    'Position',[.04 .17 .43 .78], ...
    'NextPlot','add',...
    'Xlim', [0 20], ...
    'Ylim', [1 120], ...
    'Color', [25/255 25/255 25/255], ...
    'Xcolor', [0.6 0.6 0.6], ...
    'YColor', [0.6 0.6 0.6], ...
    'Box', 'on',...
    'XGrid', 'on', ...
    'YGrid', 'on');

xlabel('Time (s)');
ylabel('Data');

%% Graph
SensorData3 = surf( NaN(2) )  ;     %// create an empty "surface" object
shading flat;
cbh=colorbar(...
    'LineWidth',1.5,...
	'Box','on',... 
	'YAxisLocation','Right',...
	'Xcolor', [0.6 0.6 0.6], ...
	'YTick',[0 1]);
 cbh.Ticks = linspace(0, 1, 10) ; %Create 8 ticks from zero to 1
 cbh.TickLabels = num2cell(1:10) ;    %Replace the labels of these 8 ticks with the numbers 1 to 8
%% Selecting the display type
uicontrol('Parent',hsp21,...
    'Style', 'text', ...
    'String', 'TIME SCALE:',...
    'Units', 'normalized', ...
    'Position',[.1 .7 .3 .2], ...
    'HorizontalAlign', 'left', ...
    'FontSize', 8,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'ForegroundColor', 'white')
h1 = uibuttongroup('Parent',hsp21,...
    'Units', 'pixels', ...
    'Units', 'normalized', ...
    'Position',[.1 .1 .3 .4], ...
	'BackgroundColor',[25/255 25/255 25/255], ...
    'BorderType', 'none');
uicontrol('Style','Radio', ...
    'Tag', 'full', ...
    'String','FULL TIME',...
	'Units', 'normalized', ...
    'Position',[.0 .5 1 .5], ...
    'FontSize', 8, ...
    'BackgroundColor', [25/255 25/255 25/255],...
	'ForegroundColor', 'white', ...
    'parent',h1, ...
    'HandleVisibility','off', ...
	'HorizontalAlign', 'left', ...
    'Value', 0);
uicontrol('Style','Radio', ...
    'Tag', 'section', ...
    'String','10s SECTION',...
	'Units', 'normalized', ...
    'Position',[.0 .0 1 .5], ...
    'FontSize', 8, ...
    'BackgroundColor', [25/255 25/255 25/255],...
	'ForegroundColor', 'white', ...
    'parent',h1, ...
    'HandleVisibility','off', ...
	'HorizontalAlign', 'left', ...
    'Value', 1);

%% Selecting gain
uicontrol('Parent',hsp21,...
    'Style', 'text', ...
    'String', 'GAIN',...
    'Units', 'normalized', ...
    'Position',[.5 .7 .4 .2], ...
    'HorizontalAlign', 'left', ...
    'FontSize', 8,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'ForegroundColor', 'white')
h2 = uibuttongroup('Parent',hsp21,...
    'Units', 'pixels', ...
    'Units', 'normalized', ...
    'Position',[.5 .1 .4 .6], ...
	'BackgroundColor',[25/255 25/255 25/255], ...
    'BorderType', 'none');
uicontrol('Style','Radio', ...
    'Tag', 'gainx1', ...
    'String','x1',...
	'Units', 'normalized', ...
    'Position',[.0 .6 .3 .3], ...
    'FontSize', 8, ...
    'BackgroundColor', [25/255 25/255 25/255],...
	'ForegroundColor', 'white', ...
    'parent',h2, ...
    'HandleVisibility','off', ...
	'HorizontalAlign', 'left', ...
    'Value', 0);
uicontrol('Style','Radio', ...
    'Tag', 'gainx2', ...
    'String','x2',...
	'Units', 'normalized', ...
    'Position',[.3 .6 .3 .3], ...
    'FontSize', 8, ...
    'BackgroundColor', [25/255 25/255 25/255],...
	'ForegroundColor', 'white', ...
    'parent',h2, ...
    'HandleVisibility','off', ...
	'HorizontalAlign', 'left', ...
    'Value', 0);
uicontrol('Style','Radio', ...
    'Tag', 'gainx4', ...
    'String','x4',...
	'Units', 'normalized', ...
    'Position',[.6 .6 .3 .3], ...
    'FontSize', 8, ...
    'BackgroundColor', [25/255 25/255 25/255],...
	'ForegroundColor', 'white', ...
    'parent',h2, ...
    'HandleVisibility','off', ...
	'HorizontalAlign', 'left', ...
    'Value', 0);
uicontrol('Style','Radio', ...
    'Tag', 'gainx5', ...
    'String','x5',...
	'Units', 'normalized', ...
    'Position',[.0 .3 1 .3], ...
    'FontSize', 8, ...
    'BackgroundColor', [25/255 25/255 25/255],...
	'ForegroundColor', 'white', ...
    'parent',h2, ...
    'HandleVisibility','off', ...
	'HorizontalAlign', 'left', ...
    'Value', 0);
uicontrol('Style','Radio', ...
    'Tag', 'gainx8', ...
    'String','x8',...
	'Units', 'normalized', ...
    'Position',[.3 .3 1 .3], ...
    'FontSize', 8, ...
    'BackgroundColor', [25/255 25/255 25/255],...
	'ForegroundColor', 'white', ...
    'parent',h2, ...
    'HandleVisibility','off', ...
	'HorizontalAlign', 'left', ...
    'Value', 0);
uicontrol('Style','Radio', ...
    'Tag', 'gainx10', ...
    'String','x10',...
	'Units', 'normalized', ...
    'Position',[.6 .3 1 .3], ...
    'FontSize', 8, ...
    'BackgroundColor', [25/255 25/255 25/255],...
	'ForegroundColor', 'white', ...
    'parent',h2, ...
    'HandleVisibility','off', ...
	'HorizontalAlign', 'left', ...
    'Value', 0);
uicontrol('Style','Radio', ...
    'Tag', 'gainx16', ...
    'String','x16',...
	'Units', 'normalized', ...
    'Position',[.0 .0 1 .3], ...
    'FontSize', 8, ...
    'BackgroundColor', [25/255 25/255 25/255],...
	'ForegroundColor', 'white', ...
    'parent',h2, ...
    'HandleVisibility','off', ...
	'HorizontalAlign', 'left', ...
    'Value', 0);
uicontrol('Style','Radio', ...
    'Tag', 'gainx32', ...
    'String','x32',...
	'Units', 'normalized', ...
    'Position',[.3 .0 1 .3], ...
    'FontSize', 8, ...
    'BackgroundColor', [25/255 25/255 25/255],...
	'ForegroundColor', 'white', ...
    'parent',h2, ...
    'HandleVisibility','off', ...
	'HorizontalAlign', 'left', ...
    'Value', 0);

%% Filtration panel
uicontrol('Parent',hsp22,...
    'Style', 'text', ...
    'String', 'FILTERS',...
    'Units', 'normalized', ...
    'Position',[.05 .7 .2 .2], ...
    'HorizontalAlign', 'left', ...
    'FontSize', 8,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'ForegroundColor', 'white')
uicontrol('Parent',hsp22,...
    'Style', 'checkbox', ...
    'Tag', 'Bandpass', ...
    'String', 'BANDPASS',...
    'Units', 'normalized', ...
    'Position',[.05 .4 .15 .2], ...
    'HorizontalAlign', 'left', ...
    'FontSize', 8,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'ForegroundColor', 'white');
uicontrol('Parent',hsp22,...
    'Style', 'text', ...
    'String', 'LOW FREQUENCY:',...
    'Units', 'normalized', ...
    'Position',[.3 .4 .2 .2], ...
    'HorizontalAlign', 'left', ...
    'FontSize', 8,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'ForegroundColor', 'white')
uicontrol('Parent',hsp22,...
    'Style', 'edit', ...
    'Tag', 'W1_pass', ...
    'String', '10',...
    'Units', 'normalized', ...
    'Position',[.52 .4 .1 .2], ...
    'HorizontalAlign', 'center', ...
    'FontSize', 8,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'ForegroundColor', 'white')
uicontrol('Parent',hsp22,...
    'Style', 'text', ...
    'String', 'HIGH FREQUENCY:',...
    'Units', 'normalized', ...
    'Position',[.65 .4 .2 .2], ...
    'HorizontalAlign', 'left', ...
    'FontSize', 8,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'ForegroundColor', 'white')
uicontrol('Parent',hsp22,...
    'Style', 'edit', ...
    'Tag', 'W2_pass', ...
    'String', '80',...
    'Units', 'normalized', ...
    'Position',[.87 .4 .1 .2], ...
    'HorizontalAlign', 'center', ...
    'FontSize', 8,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'ForegroundColor', 'white')

uicontrol('Parent',hsp22,...
    'Style', 'checkbox', ...
    'Tag', 'Bandstop50', ...
    'String', 'Notch 50 Hz',...
    'Units', 'normalized', ...
    'Position',[.05 .22 .15 .2], ...
    'HorizontalAlign', 'left', ...
    'FontSize', 8,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'ForegroundColor', 'white');
uicontrol('Parent',hsp22,...
    'Style', 'checkbox', ...
    'Tag', 'Bandstop60', ...
    'String', 'Notch 60 Hz',...
    'Units', 'normalized', ...
    'Position',[.05 .05 .2 .2], ...
    'HorizontalAlign', 'left', ...
    'FontSize', 8,...
    'BackgroundColor', [25/255 25/255 25/255], ...
    'ForegroundColor', 'white');
